Variables:
# Dear Bug Hunter,
# This credential is intentionally included for educational purposes only and does not provide access to any production systems.
# Please do not submit it as part of our bug bounty program.
  metaproc:
    Url: http://localhost:8080
    Username: admin
    Password: 1234
